In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [2]:
homedata =pd.read_csv('homedata.csv')
homedata.shape
homedata.head()
homedata.columns
X = homedata.iloc[:,[3,4,5,8]].values
Y = homedata['price'].values

In [3]:
sc = StandardScaler()

In [4]:
X = sc.fit_transform(X)
Y = sc.fit_transform(Y.reshape(-1,1))

C:\Users\Akhilesh Kr. Pandey\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Akhilesh Kr. Pandey\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
X

array([[-0.39873715, -1.44746357, -0.97983502, -0.08717263],
       [-0.39873715,  0.1756067 ,  0.53363434, -0.08717263],
       [-1.47395936, -1.44746357, -1.42625404, -0.08717263],
       ...,
       [-1.47395936, -1.77207762, -1.15404732, -0.08717263],
       [-0.39873715,  0.50022075, -0.52252773, -0.08717263],
       [-1.47395936, -1.77207762, -1.15404732, -0.08717263]])

In [6]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=10)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
reg = LinearRegression().fit(X,Y)

In [9]:
y_pred = reg.predict(x_test)

In [10]:
mean_squared_error(y_test,y_pred)

0.46514472890271186

In [11]:
transform_pred = sc.inverse_transform(y_pred)

In [12]:
transform_pred[:10]

array([[ 555433.12866004],
       [ 545671.75394722],
       [ 154328.19331036],
       [ 351897.11731303],
       [ 388514.71892724],
       [ 329442.34749911],
       [ 559864.36593002],
       [ 359094.61825759],
       [ 343837.34938825],
       [1472711.27488195]])

In [13]:
y_test_transf = sc.inverse_transform(y_test)

In [14]:
y_test_transf[:10]

array([[ 323000.],
       [ 690000.],
       [ 142000.],
       [ 560000.],
       [ 545000.],
       [ 259500.],
       [ 420000.],
       [ 305000.],
       [ 261500.],
       [1155000.]])

In [15]:
mse = mean_squared_error(y_test_transf,transform_pred)

In [16]:
rmse = np.sqrt(mse)

In [17]:
print(mse,rmse)

62690411962.41152 250380.53431209768


In [18]:
for i in range(10):
    print('Actual: {} , Prediction: {}'.format(y_test_transf[i],transform_pred[i]))

Actual: [323000.] , Prediction: [555433.12866004]
Actual: [690000.] , Prediction: [545671.75394722]
Actual: [142000.] , Prediction: [154328.19331036]
Actual: [560000.] , Prediction: [351897.11731303]
Actual: [545000.] , Prediction: [388514.71892724]
Actual: [259500.] , Prediction: [329442.34749911]
Actual: [420000.] , Prediction: [559864.36593002]
Actual: [305000.] , Prediction: [359094.61825759]
Actual: [261500.] , Prediction: [343837.34938825]
Actual: [1155000.] , Prediction: [1472711.27488195]
