In [2]:
import numpy as np

In [6]:
x = np.array([i for i in range(0,10)])


In [7]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
y = np.array(x)

In [10]:
y = np.array([1,2,3,10.5])

In [11]:
print(y)

[ 1.   2.   3.  10.5]


In [12]:
y1 = np.array([1,2.3,4.5,"hello"])

In [13]:
print(y1)

['1' '2.3' '4.5' 'hello']


In [14]:
y1.shape #order

(4,)

In [15]:
y1.ndim #n no of dimensions

1

In [16]:
print(y1[0:2]) #slicing

['1' '2.3']


In [18]:
x1 = np.array([[1,2,4],[3,4,6],[8,9,0]])

In [19]:
print(x1)

[[1 2 4]
 [3 4 6]
 [8 9 0]]


In [20]:
x1.shape

(3, 3)

In [21]:
x1.ndim

2

In [22]:
print(x1[0:2])

[[1 2 4]
 [3 4 6]]


In [24]:
print(x1[0:2][0:1])

[[1 2 4]]


In [26]:
print(x1[0:2,0:2]) #x[row][col] slicing

[[1 2]
 [3 4]]


In [27]:
#x3 =[]
#for i in range(0,10):
    #x3.append(i)
x3 = np.array([i for i in range(0,10)])

In [28]:
x4 = x1.reshape(1,9)

In [29]:
print(x4)

[[1 2 4 3 4 6 8 9 0]]


In [30]:
x5 = x4.T


In [31]:
print(x5)

[[1]
 [2]
 [4]
 [3]
 [4]
 [6]
 [8]
 [9]
 [0]]


In [32]:
x5.flatten()

array([1, 2, 4, 3, 4, 6, 8, 9, 0])

In [34]:
#first method 
#np.array()
#second method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.linspace(1,10,)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
np.linspace(1,10,num=10,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [51]:
#ravi4all

In [3]:
np.random.random() #0-1 random number

0.3816447685215756

In [4]:
np.random.random(size=(2,2))#returns 2x2 array of random numbers b/w 0-1

array([[0.34634112, 0.5968189 ],
       [0.38369373, 0.81665098]])

In [5]:
np.random.randint(5,50,10)#returns 10 random numbers b/w 5-50

array([49, 36, 17,  8, 43, 37, 44, 46, 39, 38])

In [6]:
np.random.randn(5,5) #returns any random floats of 5x5 order array

array([[-0.25983495, -0.31770886,  1.14022309,  0.98882863, -1.27980882],
       [-0.78749363,  0.5831896 , -1.06303671, -0.85623386,  0.78301051],
       [ 3.30513222,  0.82410302, -0.34987597,  0.37760349,  0.15571884],
       [-0.0292965 , -0.36249376,  0.06366515, -0.77848497, -0.79701121],
       [-0.0354617 , -1.15524302,  1.75019042, -0.62606361,  0.0189485 ]])

In [10]:
np.random.seed(0)

In [12]:
np.random.randint(5,50,10)

array([11, 29, 29, 17,  6, 43, 44, 28, 29, 22])

In [23]:
#numpy methods
arr = np.random.randint(1,100,100)

In [16]:
arr.min()

1

In [17]:
arr.max()

99

In [18]:
arr.argmin()

32

In [19]:
arr.argmax()

91

In [24]:
arr.argsort()

array([28, 89,  2, 38, 23, 96, 39, 55, 19, 86, 22, 57, 42, 76, 53, 14, 62,
       82, 30, 45, 10, 65,  0, 79, 63, 93, 37, 66, 48, 13, 64, 36, 75, 26,
       72, 71,  5, 98, 18, 29, 87, 83, 43, 81, 15, 32, 21, 91, 31,  9, 12,
       24, 50, 27, 84, 78, 33, 61, 16,  1, 34, 68, 52, 69,  4, 17, 49, 94,
       56,  7, 51, 73, 77, 47, 44, 60, 97, 35, 59, 85, 80, 25, 67, 11,  8,
       95, 70, 74, 99, 20, 58, 92, 88, 40,  6, 46, 90, 54,  3, 41],
      dtype=int64)

In [25]:
arr.sort()

In [26]:
arr.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 12, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 26, 25, 23, 24, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 37, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 48, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 60, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 74, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [27]:
arr.mean()

49.55

In [28]:
#seventh method of creating arrays
np.arange(1,100,10)
#generates 1-D array from start

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])